### ISSUE TITLE
Loyalty options need GUI controls for real-time adjustment.

### ISSUE THREAD

**Issue by BioGenx2b** [jdbener/BennerBot#11]
Having to restart the bot every time I make a small change is a bit hassling.

**Comment by jdbener** [comment]
This is not a bug, it is a development strategy, i am realising unoptimized features to the config file only, this allows me to focus on fixing bugs without worrying about having to change the way it is implemented in the GUI. Running the bot in "Lite" mode will enable realtime config file changes.

**Comment by BioGenx2b** [comment]
So just save the new config and that's it? Instantly loaded?

**Comment by jdbener** [comment]
If run in "Lite" mode, it was going to be implemented into the gui also, but i had problems pulling from both
